export const EMPLOYEES_JSON_URl = './data/employees.json';
export const CLIENTS_JSON_URL = './data/clients.json';
export const HEADER_HEIGHT = 74;
export const LINKS_ICON_MAP = new Map();
LINKS_ICON_MAP.set('www.facebook.com', ['fab', 'fa-facebook']);
LINKS_ICON_MAP.set('twitter.com', ['fab', 'fa-twitter']);
LINKS_ICON_MAP.set('www.linkedin.com', ['fab', 'fa-linkedin']);
LINKS_ICON_MAP.set('www.google-plus.com', ['fab', 'fa-google-plus']);
LINKS_ICON_MAP.set('dribbble.com', ['fab', 'fa-dribbble']);
LINKS_ICON_MAP.set('www.instagram.com', ['fab', 'fa-instagram']);